name: Workflow lors d'un push
on: push

jobs:
  docker:
    if: ${{ github.ref == 'refs/heads/main' }} 
    runs-on: ubuntu-latest
    steps:
      - name: Login dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/tp .
      - name: Push docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/tp