name: Workflow lors d'un push
on: push
jobs:
  build:
    name: Build test and run application
    runs-on: ubuntu-latest
    steps:
      - name: Récupération de notre application
        uses: actions/checkout@v4
      - name: Installation des dépendances
        run: npm install
      - name: cache npm
        uses: actions/cache@v4
        with:
          path: ~/ .npm
          key: ${{ runner.os }}-node-package-${{ hashFiles('**/package-lock.json') }}
      - name: Build de l'application Node.js
        run: npm run build
      - name: Build de l'application Flask
        run: 
      - name: Build de l'application Worker
        run: 
      - name: Upload build
        if: ${{ success() && github.ref == 'refs/heads/main' }} 
        uses: actions/upload-artifact@v4
        with: 
          name: tp
          path: build
  download:
    if: ${{ github.ref == 'refs/heads/main' }} 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Récupération de l'artefact
        uses: actions/download-artifact@v4
        with:
          name: tp
  docker:
    if: ${{ github.ref == 'refs/heads/main' }} 
    runs-on: ubuntu-latest
    needs: download
    steps:
      - name: Login dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/tp .
      - name: Push docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/tp